name: 'Repo Stats Action'
description: 'Fetch repository code frequency statistics'
inputs:
  github-token:
    description: 'GitHub token for API authentication'
    required: true
  owner:
    description: 'Repository owner'
    required: true
  repo:
    description: 'Repository name'
    required: true
outputs:
  stats:
    description: 'Repository code frequency statistics'
runs:
  using: 'node20'
  main: 'dist/index.js'
