name: Update Wakapi Stats
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'data/**'  # Ignore changes to data directory
  schedule:
    - cron: '0 17 * * *'  # Run daily at 5:00 PM UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  update_stats:
    runs-on: ubuntu-latest
    # Skip if the push was from github-actions bot
    if: github.actor != 'github-actions[bot]'
    permissions:
      contents: write
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'  # Add npm cache for faster installations
                   
      - name: Install dependencies
        run: npm ci
        
      - name: Generate Stats
        run: node src/index.js
        env:
          WAKAPI_TOKEN: ${{ secrets.WAKAPI_TOKEN }}
          WAKAPI_USERNAME: ${{ secrets.WAKAPI_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Setup and push to data branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Save data directory content
          mkdir -p /tmp/data-backup
          cp -r data/* /tmp/data-backup/ || true
          
          git checkout --orphan data
          
          git rm -rf .
          git clean -fdx

          mkdir -p data
          cp -r /tmp/data-backup/* data/ || true

          git add data/
          git commit -m "Update stats for ${{ github.run_id }}" || exit 0
          git push origin data --force
