name: Run Repo Stats Action
on: [push]  # This will run the action on every push

jobs:
  repo_stats_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get Coding Stats
        uses: ./
        with:
          wakapi-token: ${{ secrets.WAKAPI_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
