name: Update Wakapi Stats
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'data/**'  # Ignore changes to data directory
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  update_stats:
    runs-on: ubuntu-latest
    # Skip if the push was from github-actions bot
    if: github.actor != 'github-actions[bot]'
    permissions:
      contents: write
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'  # Use latest LTS version
          cache: 'npm'  # Add npm cache for faster installations
                   
      - name: Install dependencies
        run: npm ci
        
      - name: Generate Stats
        run: node src/index.js
        env:
          WAKAPI_TOKEN: ${{ secrets.WAKAPI_TOKEN }}
          WAKAPI_USERNAME: ${{ secrets.WAKAPI_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Setup and push to data branch
        run: |
          # Configure git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Save data directory content
          mkdir -p /tmp/data-backup
          cp -r data/* /tmp/data-backup/ || true
          
          # Create a new orphan branch
          git checkout --orphan data
          
          # Remove everything
          git rm -rf .
          git clean -fdx
          
          # Restore data
          mkdir -p data
          cp -r /tmp/data-backup/* data/ || true
          
          # Commit and push
          git add data/
          git commit -m "Update stats for ${{ github.run_id }}" || exit 0
          git push origin data --force
