name: Update Wakapi Stats
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'data/**'  # Ignore changes to data directory
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  update_stats:
    runs-on: ubuntu-latest
    # Skip if the push was from github-actions bot
    if: github.actor != 'github-actions[bot]'
    permissions:
      contents: write
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          ref: main  # Explicitly checkout main branch first

      - name: Setup data branch
        run: |
          git fetch origin data || true  # Try to fetch data branch, don't fail if it doesn't exist
          git checkout -b data || git checkout data  # Create or checkout existing data branch
          git reset --hard origin/main  # Reset to main branch content
          git push origin data --force || true  # Force push to data branch, don't fail if first time

      - name: Install canvas dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'  # Use latest LTS version
                   
      - name: Install dependencies
        run: npm ci
        
      - name: Generate Stats
        run: node src/index.js
        env:
          WAKAPI_TOKEN: ${{ secrets.WAKAPI_TOKEN }}
          WAKAPI_USERNAME: ${{ secrets.WAKAPI_USERNAME }}

      - name: Commit and push to data branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add data/
          git commit -m "Update stats for ${{ github.run_id }}" || exit 0
          git push origin data
